### ISSUE TITLE
Feature request: add custom channel

### ISSUE THREAD

**Issue by colbin8r** [simon--poole/ev-browser-extension-chrome#2]
I think it would be great if folks could add additional channels not in the specified list. That would make this plugin applicable to any YouTube channel with regularly syndicated content (i.e. non-e-sports replays).

If this is a feature you'd like me to add, I would consider creating a PR for it.

**Comment by simon--poole** [comment]
For now we don't want people to be able to add certain channels.
If you have particular esports channels you'd like added, feel free to let me know and I can add them - or add them yourself in a PR.  
I'd suggest if you want non-esports replays it might be worth forking a spinoff, since obviously we at EventVODs are focused on esports.

**Comment by werkaster** [comment]
Why in the world don't you want people to add certain channels so the extension can grow? Is it because Youtube is closing some of these channels maybe? Very well, that's okay I guess, your plugin, your rules :) But at the moment most of the crucial channels are missing, at least the best games and the ones that have most games/update the most. It's a great idea to add these I think and I will do my best to spread the word. At the moment I haven't much use for this add-on I'm afraid. Good luck with the project! 

**Hearthstone**
HearthStone Matches
HearthVoDs
GameVODS *Other games too I think
Hearthstone Pro Players Reloaded *Not as important as the others, but some people only watch this.

**Counterstrike**
ESL Counter-Strike
CS:GO Coverage
CS:GO VODS

**Starcraft 2**
eSportsTV_Global
아프리카TV (AfreecaTV) *This is the whole channel name, symbols, () and everything. English casting. 
GOM eXP Official *Old channel for SC2 before AfreecaTV took over, but they have several years of whole tournaments still here. Great for rewatches.

**Rocket League**
eSports Replays *Also A LOT of different games here
Rocket League Esports
MajorLeagueGaming
SubParButInHD *minor channel
Xenill | Gaming *minor channel

With best regards,
Daniel
